[package]
name = "authly"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
axum = "0.8.4"
base64 = "0.22.1"
once_cell = "1.21.3"
serde = "1.0.219"
serde_json = "1.0.142"
tokio = "1.47.1"
